<?php
/*
 * Copyright (c) 2025.
 * Petr Ciahotný
 */

class History extends GameBase
{
    protected static ?History $instance = null;

    protected function __construct()
    {
        parent::__construct();
    }

    public static function getInstance(): self
    {
        if (self::$instance == null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    public function init(): void
    {
     //   parent::init(); // TODO: Change the autogenerated stub
    }

    protected function getHistoryList() : array
    {
        $sql = "SELECT b.*,  CASE WHEN uzivatel1 = :uziv_id THEN b.uzivatel2 ELSE b.uzivatel1 END AS opponent, u.jmeno opponent_name  
            FROM lode.bitvy b
            INNER JOIN lode.uzivatele u ON u.id = CASE WHEN uzivatel1 = :uziv_id THEN b.uzivatel2 ELSE b.uzivatel1 END
            WHERE :uziv_id IN (b.uzivatel1, b.uzivatel2) 
            ORDER BY b.cas_start";
         return Db::select($sql, ['uziv_id'=>$_SESSION['id']]);
    }

    public function render(): void
    {

        $id = -1;
        if (GameBase::getParamByKey(0) == 'history') {
             $id = GameBase::getParamByKey(1) ?? -1;
        }
        Game::getInstance()->resetCurrentState();
        Game::getInstance()->resetCurrentGame();

        $games = $this->getHistoryList();
        ?>
        <div>Historie</div>
         <?php foreach ($games as $game) {
             ?>
            <div style="border:solid 1px black; padding: 10px;
                    background-color: <?= $game['vitez'] == $_SESSION['id'] ? 'lightgreen' : 'pink' ?> ">
                <a href="<?= GameBase::getLinkUrl("/game/show-game/{$game['id']}") ?>">
                    <?= $game['id'] ?></a>
                <?= $game['cas_start'] ?>
                <?= $game['opponent'] ?>
                <?= $game['opponent_name'] ?>
                ?>
            </div>
        <?php }
    }
}